directories:
  output: release
  buildResources: build
productName: Project Manga App
copyright: ''
asar: true
win:
  target: NSIS
nsis:
  oneClick: false
  perMachine: true
  allowElevation: true
  allowToChangeInstallationDirectory: true
  runAfterFinish: true
  license: LICENSE
  deleteAppDataOnUninstall: true
electronVersion: 4.0.1
